

services:
  weather_microservice:
    image: weather-fastapi:1.0
    ports:
    - "8000:8000"
  regije_mikroservice:
    image: aiohttp-regije:1.0
    ports:
    - "4000:4000"

networks:
  interna_mreza:
    driver: bridge
